### ISSUE TITLE
어떤 온맵파일은 불어오는 도중 멈춰버립니다.

### ISSUE THREAD

**Issue by queenmedley** [Gaia3D/OnMapLoader#6]
얼마전 한글코딩 문제로 인한 문제로 글을 올렸었는데요.
이전 문제 해결하신 후 제가 테스트한 온맵파일은 불러오는게 잘됐엇는데요..
온맵파일 중 어떤건 불러오는 도중 멈춰버립니다.
아래 최근에 받은 샘플입니다.
https://www.dropbox.com/s/zp3hgduszmix8gh/%28B090%29%EC%98%A8%EB%A7%B5_358124.pdf?dl=0

**Comment by jangbi882** [comment]
감사합니다.
보내주신 파일 저도 해봤는데 멈추네요.
제가 생각 못한 예외인 듯 합니다.

설 기간에 시간을 내서 좀 보도록 하겠습니다.

관심가지시고 피드백 해 주셔서 도움이 많이 되고 있습니다.
감사합니다.

명절 잘 보내십시오.

**Comment by jangbi882** [comment]
아주 오~~~~래 기다리면 되기는 하는데 일부 레이어는 오류가 나요.
1:2만5천은 생각보다 시간이 많이 걸리는데 특히 이 도엽은 등고선이 엄청 많아 더 시간이 걸리네요.

오류는 잡겠는데 오래 걸리는 것은 어찌 대응해야 할지...

**Comment by jangbi882** [comment]
일부 레이어의 폴리곤을 불러오던 중 나는 오류는 모두 수정되었습니다.
다음에서 받으실 수 있습니다.
https://github.com/Gaia3D/OnMapLoader/raw/master/release/OnMapLoader_1.3.zip

하지만, 1:25,000 등 넓은 범위를 포함하고 용량이 큰 파일에서 정보를 가져오는 동안
화면이 죽은 듯이 멈추는 문제는 해결 방법이 없네요.
멀티스레드도 이 부분에서는 정상동작이 안됩니다.
보내주신 파일은 오래(십분 정도) 기다리면 열리기는 합니다.

일단 1:5000이 아닌 경우 경고를 띄우는 정도에서 마무리 합니다.
